---
- name: SRILM | Compilation | Ensure SRILM directory exists.
  file: path={{ srilm_path }} state=directory owner=root group=root mode=755

- name: SRILM | Compilation | Extract SRILM tarball.
  command: tar -xz --directory {{ srilm_path }} -f /vagrant/provisioning/srilm.tgz

- name: SRILM | Compilation | Update PATH in Makefile.
  command: perl -p -i -e 's!^#\s+(SRILM = )/home/speech/stolcke/project/srilm/devel\E!$1/opt/srilm!' {{ srilm_path }}/Makefile

- name: SRILM | Compilation | Compile.
  command: make -C {{ srilm_path }}
  environment:
    NO_TCL: 'X'
    TCL_INCLUDE: ''
    TCL_LIBRARY: ''
