---
- name: SRILM | Packages | Install required system packages.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - git
    - python-dev
    - python-pip
    - libyaml-dev
    - swig
  tags:
    - srilm
    - packages

