---
- name: SWIG | Clone swig-srilm git repository.
  git:
    repo: https://github.com/desilinguist/swig-srilm 
    dest: "{{swig_srilm}}"

- name: SWIG | Register abbreviated architecture as variable.
  shell: uname -m
  register: uname_m

- name: SWIG | Update library directories in Makefile (1/3).
  lineinfile: >
    dest={{swig_srilm}}/Makefile
    state=present
    regexp='^SRILM_LIBS='
    line="SRILM_LIBS={{srilm_path}}/lib/{{uname_m.stdout}}"

- name: SWIG | Update library directories in Makefile (2/3).
  lineinfile: >
    dest={{swig_srilm}}/Makefile
    state=present
    regexp='^SRILM_INC='
    line="SRILM_INC={{srilm_path}}/include"

- name: SWIG | Update library directories in Makefile (3/3).
  lineinfile: >
    dest={{swig_srilm}}/Makefile
    state=present
    regexp='^PYTHON_INC='
    line="PYTHON_INC=/usr/include/python2.7"

- name: SWIG | Compile.
  command: make -C {{swig_srilm}}

