---
- name: Download all corpora.
  command: python -m nltk.downloader -d {{ nltk_data }}
  tags:
    - packages

- name: Download punkt tokenizer.
  command: python -m nltk.downloader -d "punkt"
  tags:
    - packages
