---
- name: Install package dependencies.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=true
  with_items:
    - git
    - build-essential
    - python-pip
    - python-dev
  tags:
    - packages

- name: Install nltk via pip.
  pip: package=nltk extra_args='--upgrade'
  tags:
    - packages

