---
- name: Force /bin/sh -> /bin/bash
  command: ln -s -f bash /bin/sh

- name: Ensure Kaldi LM  directory exists.
  file: path={{ kaldilm_path }} state=directory owner=root group=root mode=755

- name: Checkout repository.
  command: svn co https://kaldi.svn.sourceforge.net/svnroot/kaldi/trunk {{ kaldilm_path }}

- name: Compile tools.
  command: make -C {{ kaldilm_path }}/tools

- name: Configure source.
  command: ./configure chdir={{ kaldilm_path }}/src

- name: Build.
  command: make -C {{ kaldilm_path }}/src


