---
- name: Ensure Kaldi LM  directory exists.
  file: path={{ kaldilm_path }} state=directory owner=root group=root mode=755

- name: Checkout repository.
  command: svn co https://kaldi.svn.sourceforge.net/svnroot/kaldi/trunk {{ kaldilm_path }}

- name: Compile.
  command: make -C {{ kaldilm_path }}

