---
- name: Install required system packages.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - subversion
    - autoconf
    - automake 
    - libtool
    - libatlas-dev
    - libatlas-base-dev
  tags:
    - kaldilm
    - packages

