---
- name: Install homesick Ruby gem.
  command: bash -lc "gem install homesick"
  # It would be nice to use the "gem" ansible module, 
  # but unfortunately it fails often. See here for info: 
  # http://stackoverflow.com/a/22121802/140800
  # gem: name=homesick state=latest

  # For the life of me, I can't figure out why cloning via homesick hangs.
  # So let's just pull down the repo using the "git" module, 
  # which means we have to ensure the target directory exists.

#- name: Add dotfiles as Homesick castle.
#  command: homesick clone https://github.com/ronocdh/dotfiles/
#  sudo: false

- name: Ensure dotfiles directory exists.
  command: mkdir -p /home/vagrant/.homesick/repos/dotfiles
  sudo: false

- name: Add github.com host key to system-wide known_hosts.
  shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

- name: Clone dotfiles git repository.
  git: 
    repo: https://github.com/ronocdh/dotfiles.git
    dest: /home/vagrant/.homesick/repos/dotfiles
    version: fix-submodules
    accept_hostkey: true
  sudo: false

- name: Deploy homesick symlinks.
  command: homesick symlink --force dotfiles
  sudo: false
